import { createMemoryTable } from './table.ts';
import type { EngineStore } from '../../ports/store.ts';

export const createMemoryStore = (): EngineStore => ({
  actors: createMemoryTable(),
  aliases: createMemoryTable(),
  sessions: createMemoryTable(),
  experiences: createMemoryTable(),
  mediaAssets: createMemoryTable(),
  uploadTargets: createMemoryTable(),
  transcripts: createMemoryTable(),
  replies: createMemoryTable(),
  reactions: createMemoryTable(),
  fairVotes: createMemoryTable(),
  counters: createMemoryTable(),
  feedEntries: createMemoryTable(),
  reports: createMemoryTable(),
  queueItems: createMemoryTable(),
  moderationActions: createMemoryTable(),
  screenings: createMemoryTable(),
  searchDocuments: createMemoryTable(),
  subjects: createMemoryTable(),
  experienceSubjects: createMemoryTable(),
  graphEdges: createMemoryTable(),
  notifications: createMemoryTable(),
  notificationPreferences: createMemoryTable(),
  reputation: createMemoryTable(),
  rankingInputs: createMemoryTable(),
  trends: createMemoryTable(),
  deletionRequests: createMemoryTable(),
  exportRequests: createMemoryTable(),
  auditEvents: createMemoryTable(),
  roleAssignments: createMemoryTable(),
  analyticsEvents: createMemoryTable(),
  metricSnapshots: createMemoryTable(),
});
