import { createMemoryTable } from './table.ts';
import type { EngineStore } from '../../ports/store.ts';

export const createMemoryStore = (): EngineStore => ({
  actors: createMemoryTable(),
  aliases: createMemoryTable(),
  sessions: createMemoryTable(),
  experiences: createMemoryTable(),
  mediaAssets: createMemoryTable(),
  uploadTargets: createMemoryTable(),
  transcripts: createMemoryTable(),
  replies: createMemoryTable(),
  reactions: createMemoryTable(),
  fairVotes: createMemoryTable(),
  counters: createMemoryTable(),
  feedEntries: createMemoryTable(),
  reports: createMemoryTable(),
  queueItems: createMemoryTable(),
  moderationActions: createMemoryTable(),
  screenings: createMemoryTable(),
  searchDocuments: createMemoryTable(),
  subjects: createMemoryTable(),
  experienceSubjects: createMemoryTable(),
  graphEdges: createMemoryTable(),
  notifications: createMemoryTable(),
  notificationPreferences: createMemoryTable(),
  reputation: createMemoryTable(),
  rankingInputs: createMemoryTable(),
  trends: createMemoryTable(),
  deletionRequests: createMemoryTable(),
  exportRequests: createMemoryTable(),
  auditEvents: createMemoryTable(),
  roleAssignments: createMemoryTable(),
  analyticsEvents: createMemoryTable(),
  metricSnapshots: createMemoryTable(),
  // Experience Signal Engine
  categories: createMemoryTable(),
  issueTypes: createMemoryTable(),
  entities: createMemoryTable(),
  entityAliases: createMemoryTable(),
  locations: createMemoryTable(),
  experienceMetadata: createMemoryTable(),
  corroborations: createMemoryTable(),
  shares: createMemoryTable(),
  clusters: createMemoryTable(),
  clusterMembers: createMemoryTable(),
  evidence: createMemoryTable(),
  evidenceAssessments: createMemoryTable(),
  resolutionReports: createMemoryTable(),
  resolutionEvents: createMemoryTable(),
  organizationProfiles: createMemoryTable(),
  organizationMemberships: createMemoryTable(),
  organizationResponses: createMemoryTable(),
  trustAssessments: createMemoryTable(),
  riskEvents: createMemoryTable(),
  moderationCases: createMemoryTable(),
  signalSnapshots: createMemoryTable(),
  disputes: createMemoryTable(),
  relations: createMemoryTable(),
  responsiveness: createMemoryTable(),
  proposals: createMemoryTable(),
  enrichments: createMemoryTable(),
  severities: createMemoryTable(),
  escalations: createMemoryTable(),
  organizationCases: createMemoryTable(),
  handoffs: createMemoryTable(),
});
